language: node_js
node_js:
  - node
script:
  - npm test
  - npm run coverage
deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY 
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  glob: "*.html"
after_deploy:
  - bash aws/update_aws.sh
