before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
language: node_js
node_js:
  - node
script:
  - npm test
  - npm run coverage
after_script:
  - bash aws/update_aws.sh
