language: node_js
node_js:
  - node
script:
  - nyc mocha --reporter mochawesome
after_success:
  - nyc report --reporter=text-lcov | coveralls
before_deploy:
  - rm -rf node_modules
addons:
  artifacts: true
    paths: "mochawesome-report"
